[tool]
[tool.poetry]
name = "AndroUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy AndroUserBot to Heroku"
authors = ["HzZekSen"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
